project:
  render:
    - "*.qmd"
    - "!fr/"

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: working-papers.qmd
        text: Working papers
      - href: data.qmd
        text: Data
      - href: teaching.qmd
        text: Teaching
    right:
      - href: /fr/
        text: Français
      - icon: envelope
        href: "mailto:guay.alain@uqam.ca"
        aria-label: Email
      - icon: mortarboard-fill
        href: "https://scholar.google.com/citations?user=Swf3sB4AAAAJ"
        aria-label: Google Scholar
  page-footer:
    right: "Built with [Quarto](https://quarto.org)"
